language: python
python:
- '3.9'
sudo: false
cache:
  directories:
  - "~/.platformio"
  - "$HOME/.cache/pip"
install:
- pip install -U platformio
- pio update
script:
- export PROG_VERSION=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- pio run
before_deploy:
- pio run -e d1_mini -c platformio.ini
deploy:
  provider: releases
  api_key:
    secure: gSVrprzj3tUYnA60W9vL9xyAIrc1KwIISzz1Y7nsIh4bNoiGWelLsuq/EmNNrXpHxglVUVxLWT9iiADBy73w52G/4i2ZaYpyjC+RmR/jz1HjrGSx4XXV2BQ5MLUzjUdRjhqYkTSX3kr8H51fm7jNAXmblqnWYKg91Y31kxpU9S5B1qcHrNzIXDdXBn5Hd252L5c63wpyNSo6Qvs4OXdMyexHIXuvAFDMCEEHgnjjqwzL5m0MNfsc7pmDmv2W3Vk69yvLQH/1yh5QMUNapfvI8CVIx/wOItf861AFLjjegdchERddUFb4Z4nJKb7OJ5aYRNjXcnBl9L8PjK6z4m9qmh+K5vRqaYSJMHwnCRqkcVk6x0izT1ULAGHIDr/qHMACE3KEC8W06jpRmiyMYuoTTAo35gdlSUWxJqdXFPl5j7Rie0YNFzrx8GxISeHRSNUTYT49xWj4zCnnp/qo/a8wwBjlXVjXZQBa8bOh4bKlijXOeLxmBYfDdDl85I+YuEa/W3ub4XmxpAqQ74gl2Qok7j69n9uabWcghKDdjTPXASuhj3149YNeMgU+oIHNgsY866oPl45p6mPFNfXxX4iwdTUKRPHIFxezG2Rgdk1JBGFYvzSZTHVnILVI0py2YdxK+kAnXdhhpZFQ2kh6eLR6TV3fqDT09Fm6uZ2NcYfDgbE=
  file: ".pio/build/d1_mini/firmware.bin"
  skip_cleanup: true
  on:
    tags: true
